CREATE TABLE students
(
	StudentId INT  NOT NULL AUTO_INCREMENT,
	FirstName VARCHAR(80) NOT NULL,
	LastName VARCHAR(80) NOT NULL,
	Birthday DATE NOT NULL,
	City VARCHAR(50) NOT NULL,
	PRIMARY KEY (StudentId)
);
